spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # update ??'validate' ??? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/blog # MySQL ?? ? ?????? ??? ??
    username: root # MySQL ??? ???? ??
    password: 1234 # MySQL ????? ??
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ????? ??
